spring:
    datasource:
        driver-class-name: org.h2.Driver
        # local File
        url: jdbc:h2:file:~/data/projectTable
        # local Memory 
        # url: jdbc:h2:mem:local
        username: nick
        password: localdata

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        defer-datasource-initialization: true
        hibernate:
            # drops and recreate tables
            # ddl-auto: create-drop

            # check if table matches
            # ddl-auto: validate

            # Updates table
            ddl-auto: update
    h2:
        console.enabled: true
        console:
            path: /h2
            settings:
                trace: false 